### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [naoyashiga/RPLoadingAnimation#1]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by naoyashiga** [comment]
Please send pull request for Swift 3 💪 🙏

**Comment by naeemshaikh90** [comment]
@naoyashiga Updated for Swift 3?

**Comment by naoyashiga** [comment]
@naeemshaikh90 I have no plan to updated for swift3. please pull request. I will merge.

**Comment by naeemshaikh90** [comment]
@naoyashiga #2 I was asking for this, as this commit shows update to Swift 3.

**Comment by naoyashiga** [comment]
@naeemshaikh90 yes. updated by #2 👍

**Comment by naeemshaikh90** [comment]
Great than this issue should be closed, as it creating confusion. 😄

**Comment by naoyashiga** [comment]
OK i will close

**Comment by naeemshaikh90** [comment]
👍
